config/routes.rb
Rails.application.routes.draw do
  resources :posts
	get "/extras" => "extras#index"
	devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations"}
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
	include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
					:omniauthable
	has_many :posts, dependent: :destroy
	has_many :identities, dependent: :destroy
	has_many :extras, dependent: :destroy

	has_attached_file :image,
										styles: { medium: "300x300>", thumb: "100x100>" },
										preserve: true,
										default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	after_create :set_default_role
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
 	def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name   # assuming the user model has a name
			user.image = auth.info.image # assuming the user model has an image
		end
	end
	 def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      # email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      # email = auth.info.email if email_is_verified
      # user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
				if !auth.info.email.nil?
						user = User.new(
						name: auth.info.name || auth.extra.nickname ||  auth.uid,
						email: User.where(:email => auth.info.email).first ? "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com" : auth.info.email,
						image: auth.info.image ? auth.info.image : nil,
						password: Devise.friendly_token[0,20]
						)
				else
						user = User.new(
						name: auth.info.name || auth.extra.nickname ||  auth.uid,
						email: "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
						image: auth.info.image ? auth.info.image : nil,
						password: Devise.friendly_token[0,20]
						)
				end
      	# user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    user

  end
	private
  def set_default_role
    add_role :user
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :finish_signup

  # ...

  def finish_signup
    if request.patch? && params[:user] #&& params[:user][:email]
      if current_user.update(user_params)
        current_user.skip_reconfirmation!
        sign_in(current_user, :bypass => true)
        redirect_to current_user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def kakao
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "kakao") if is_navigational_format?
    else
      session["devise.kakao_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def naver
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "naver") if is_navigational_format?
    else
      session["devise.naver_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def daum
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "daum") if is_navigational_format?
    else
      session["devise.daum_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :finish_signup	
	def update
	end
  # ...
  def finish_signup
    if request.patch? && params[:user] #&& params[:user][:email]
      if current_user.update(user_params)
        current_user.skip_reconfirmation!
        sign_in(current_user, :bypass => true)
        redirect_to :back, notice: '확인 이메일이 전송되었습니다.'
      else
        @show_errors = true
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h2>이메일 입력</h2>
	<% if @show_errors && current_user.errors.any? %>
		<div id="error_explanation">
			<% current_user.errors.full_messages.each do |msg| %>
				<%= msg %><br>
			<% end %>
		</div>
	<% end %>
	<% if current_user.unconfirmed_email? %>
		<%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
			<div class="form-group">
				<%= f.label	:email, "확인 이메일 재전송" %>
				<div class="controls">
					<%= f.text_field :email, :value => current_user.unconfirmed_email, class: 'form-control input-lg', :readonly => true %>
					<p class="help-block">입력하신 이메일 주소로 확인 이메일이 전송됩니다.</p>
				</div>
			</div>
			<div class="actions">
				<%= f.submit '전송', :class => "btn btn-default" %>
			</div>
		<% end %>
	<% end %>
	<br><br>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <div class="form-group">
      <%= f.label :email, "새로운 이메일로 확인 이메일 전송" %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">입력하신 이메일 주소로 확인 이메일이 전송됩니다.</p>
      </div>
    </div>
    <span class="actions">
      <%= f.submit '전송', :class => 'btn btn-default' %>
    </span>
  <% end %>
</div>

app/views/users/profile.html.erb
<div class="container">
	<% if !flash[:alert].nil? %>
	<div class="aert alert-danger">
		<%= flash[:alert] %>
	</div>
	<% end %>
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4 text-center">
			<h3 class="form-heading">Edit User</h3>
			<form action="users/profile_complete" method="post">
				<input type="hidden" name="id" value="<%= @user.id %>">
				<p><input class="form-input" type="text" name="name" value="<%= @user.name %>"></p>
				<p><input class="form-input" type="text" name="email" value="<%= @user.email %>"></p>
			<input class="btn btn-lg btn-block" type="submit" value="Update">
			</form>
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>