config/routes.rb
Rails.application.routes.draw do
  resources :posts
	get "/extras" => "extras#index"
	devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations"}
	match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'welcome#index'

end

app/models/extra.rb
class Extra < ActiveRecord::Base
	resourcify
	belongs_to :user
end

app/controllers/extras_controller.rb
class ExtrasController < ApplicationController
  before_action :set_extra, only: [:show, :edit, :update, :destroy]
	before_action :login_check
	skip_before_action :login_check, :only => [:index]

  # GET /extras
  # GET /extras.json
  def index
		@subways=Subway.all	
		@colleges=College.all	
  end

  # GET /extras/1
  # GET /extras/1.json
  def show
  end

  # GET /extras/new
  def new
    @extra = Extra.new
  end

  # GET /extras/1/edit
  def edit
  end

  # POST /extras
  # POST /extras.json
  def create
    @extra = Extra.new(extra_params)

    respond_to do |format|
      if @extra.save
        format.html { redirect_to @extra, notice: 'Extra was successfully created.' }
        format.json { render :show, status: :created, location: @extra }
      else
        format.html { render :new }
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extras/1
  # PATCH/PUT /extras/1.json
  def update
    respond_to do |format|
      if @extra.update(extra_params)
        format.html { redirect_to @extra, notice: 'Extra was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra }
      else
        format.html { render :edit }
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extras/1
  # DELETE /extras/1.json
  def destroy
    @extra.destroy
    respond_to do |format|
      format.html { redirect_to extras_url, notice: 'Extra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra
      @extra = Extra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extra_params
      params[:extra]
    end
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/views/extras/_form.html.erb
<%= simple_form_for(@extra) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/extras/edit.html.erb
<h1>Editing Extra</h1>

<%= render 'form' %>

<%= link_to 'Show', @extra %> |
<%= link_to 'Back', extras_path %>

app/views/extras/index.html.erb
<div id="map" style="width:800px;height:500px;"></div>
<!-- services와 clusterer 라이브러리 불러오기 -->
<script>
var infowindow = new daum.maps.InfoWindow({zIndex:1});
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new daum.maps.LatLng(37.53569162926515, 126.94627494388307), // 지도의 중심좌표
        level: 7 // 지도의 확대 레벨
    };

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// 일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다
var mapTypeControl = new daum.maps.MapTypeControl();

// 지도에 컨트롤을 추가해야 지도위에 표시됩니다
// daum.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다
map.addControl(mapTypeControl, daum.maps.ControlPosition.TOPRIGHT);

// 지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다
var zoomControl = new daum.maps.ZoomControl();
map.addControl(zoomControl, daum.maps.ControlPosition.RIGHT);
var markers= new Array;
// 장소 검색 객체를 생성합니다
var ps = new daum.maps.services.Places(); 
daum.maps.event.addListener(map, 'tilesloaded', function() { 
	var bounds=map.getBounds();
	var swLatLng = bounds.getSouthWest();
	var neLatLng = bounds.getNorthEast();
	var Lat1 = swLatLng.getLat();
	var Lng1 = swLatLng.getLng();
	var Lat2 = neLatLng.getLat();
	var Lng2 = neLatLng.getLng();
	removeMarker();
	<% @subways.each do |s| %>
		var s_name = "<%= s.name %>";
		var s_point = new daum.maps.LatLng(<%=s.location_y %>,<%=s.location_x %>);
		if(bounds.contain(s_point)){
			displayMarker(s_point, s_name);
		}
	<% end %>
	<% @colleges.each do |c| %>
		var c_name = "<%= c.name %>";
		var c_point = new daum.maps.LatLng(<%=c.location_y %>,<%=c.location_x %>);
		if(bounds.contain(c_point)){
			displayMarker(c_point, c_name);
		}
	<% end %>
});
function removeMarker() {
    for(var i=0; i<markers.length; i++) {
			 markers[i].setMap(null);
		}   
		markers = [];
}

	// 지도에 마커를 표시하는 함수입니다
	function displayMarker(place, name) {
			
			// 마커를 생성하고 지도에 표시합니다
			var marker = new daum.maps.Marker({
					map: map,
					position: place 
			});
			markers.push(marker);
			// 마커에 클릭이벤트를 등록합니다
			daum.maps.event.addListener(marker, 'click', function() {
					// 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
					infowindow.setContent('<div style="padding:5px;font-size:12px;">' + name + '</div>');
					infowindow.open(map, marker);
			});
	}
</script>

app/views/extras/new.html.erb
<h1>New Extra</h1>

<%= render 'form' %>

<%= link_to 'Back', extras_path %>

app/views/extras/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_extra_path(@extra) %> |
<%= link_to 'Back', extras_path %>